// <auto-generated />
using BusinessLookup.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessLookup.Migrations
{
    [DbContext(typeof(BusinessLookupContext))]
    [Migration("20210611183942_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BusinessLookup.Models.LocalBusiness", b =>
                {
                    b.Property<int>("LocalBusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("RateReview")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("LocalBusinessId");

                    b.ToTable("LocalBusinesses");

                    b.HasData(
                        new
                        {
                            LocalBusinessId = 1,
                            BusinessName = "Pok Pok",
                            BusinessType = "Restaurant",
                            RateReview = 4,
                            Review = "I love this restautant. It is SE Asian inspired and the food is sooo delicious. The only downside is you do have to wait a long time"
                        },
                        new
                        {
                            LocalBusinessId = 2,
                            BusinessName = "Loving Hut",
                            BusinessType = "Restaurant",
                            RateReview = 5,
                            Review = "Even though i'm not vegan, the food here is absolutely delicious. I've eaten here numerous times and everything I've tryied is mouthwatering"
                        },
                        new
                        {
                            LocalBusinessId = 3,
                            BusinessName = "Chowder Tavern",
                            BusinessType = "Bar",
                            RateReview = 4,
                            Review = "Its a must. All their drinks are super different. I had the clammy blody mary and it was one of the best I've had"
                        },
                        new
                        {
                            LocalBusinessId = 4,
                            BusinessName = "Happy Orchid",
                            BusinessType = "Flowe Shop",
                            RateReview = 5,
                            Review = "They have a wide veriety of flowers and they also offer classes with a pretty awesome instructor"
                        },
                        new
                        {
                            LocalBusinessId = 5,
                            BusinessName = "Crazy Hammer",
                            BusinessType = "Hardware Shop",
                            RateReview = 3,
                            Review = "Its your regular well-stock hardware store. But their staff is limited and hard to get help."
                        },
                        new
                        {
                            LocalBusinessId = 6,
                            BusinessName = "Freemont",
                            BusinessType = "Grocery Shop",
                            RateReview = 5,
                            Review = "Even though its a small neighborhood store, it is very well stocked, you can find just about anything"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
